name: Parse and dispatch providers events
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dispatch-provider-events:
    name: Dispatch provider events
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.FETCH_REPO_TOKEN }}
          event-type: pr-number
          client-payload: '{"event": "${{ github.event_name }}", "number": "${{ github.event.number }}"}'
